spring:
   datasource:
     driver-class-name: com.mysql.jdbc.Driver
     url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/private_collection_manager?serverTimezone=UTC}
     username: ${SPRING_DATASOURCE_USERNAME:root}
     password: ${SPRING_DATASOURCE_PASSWORD:root}
     initialization-mode: always
   jpa:
     show-sql: true
     hibernate:
       ddl-auto: create
     database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
app:
  jwtSecret: RjeeySecretKey
  jwtExpirationMs: 86400000
