spring:
   security:
     user:
       name: rjeey
       password: rjeey
       roles: manager
   datasource:
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://localhost:3306/private_collection_manager?serverTimezone=UTC
     username: root
     password: root
     initialization-mode: always
   jpa:
     show-sql: true
     hibernate:
       ddl-auto: create-drop
     database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
app:
  jwtSecret: RjeeySecretKey
  jwtExpirationMs: 86400000
